from_owner:
  - atlet99

required_labels:
  - ready

apply_labels:
  - merge

auto_merge_labels:
  - auto-merge

auto_squash_merge_labels:
  - auto-squash-merge

auto_rebase_merge_labels:
  - auto-rebase-merge