run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gosec
        - gocritic
        - goconst
        - gocognit
        - gocyclo

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - gocognit
    - mnd

linters-settings:
  mnd:
    ignore-numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
 