#first comment
env:
  rainc: AES256:mXBWxRaddFbdZNt6VnNuKw8/l86J3GkLTym28+bkqcg=
  # AES256:F4Tkz/WhnNhvQ/jEjqv+Dvr9Dp2+WI18bcmsMKf8zrg=
  coins: AES256:ukdoRHD9fH++Pr9SO922sqezyWHUwTjsIpgk3How6GM=
str: # 3 comment
  1: 345343

  2: e5w5g345t

  aerfger:
    rrr: ffgragf
    sd: 4354

    #comment

    env:
      srfgar: AES256:piBajifwK+OWEMCOBo7aGgwT3P0CsNAONn1jHaWtWdc=
