encryption:
  # General settings from main config
  unsecure_diff: true # Set to true to show actual values in diff mode
  
  # Additional rule files (supports wildcards and ranges like rules[1-3].yml)
  include_rules:
    - "custom_rules/*.yml"
    - "specific_rules/database_rules.yml"
    - "rules/*.yml"
    # - "conflicts*.yml"  # Commented out to avoid rule conflicts in automated tests
  
  # Validate all rules for correctness (default: true)
  validate_rules: true
  
  rules:
    # Rules from main config (fixed skip_axel_fix block)
    - name: "skip_axel_fix"
      block: "axel.fix"
      pattern: "*"
      action: "none"
      description: "Skip encryption for all values in axel.fix block"
      
    # Certificates and their processing
    - name: "certificates_rule"
      block: "certificates"
      pattern: "*"
      description: "Process all certificate fields"
    
    - name: "quoted_public_key_rule"
      block: "certificates"
      pattern: "quoted_public_key"
      action: "none"
      description: "Skip encryption/decryption for quoted public key"
      
    # Existing test-specific rules
    - name: "password_rule"
      block: "smart_config.auth"
      pattern: "password"
      description: "Encrypt password field"
    - name: "api_key_rule"
      block: "api"
      pattern: "api_key"
      description: "Encrypt API keys"
    - name: "private_key_rule"
      block: "secrets"
      pattern: "private_key"
      description: "Encrypt private key"
    - name: "block_key_rule"
      block: "ssh"
      pattern: "block_key"
      description: "Encrypt block SSH key"
    - name: "string_key_rule"
      block: "ssh"
      pattern: "string_key"
      description: "Encrypt string SSH key"
    - name: "encrypt_smart_config"
      block: "smart_config"
      pattern: "**"
      description: "Encrypt all values in smart_config block"
    - name: "encrypt_passwords"
      block: "*"
      pattern: "pass*"
      description: "Encrypt all password fields globally"

    - name: "nginx_config"
      block: "nginx"
      pattern: "**"
      description: "Encrypt nginx configuration blocks"

    - name: "apache_config"
      block: "apache"
      pattern: "**"
      description: "Encrypt apache configuration blocks"

    - name: "haproxy_config"
      block: "haproxy"
      pattern: "**"
      description: "Encrypt haproxy configuration blocks"

    - name: "skip_comments"
      block: "*"
      pattern: "**"
      exclude: "#*"
      description: "Skip comments in all blocks" 