name: Branch Protection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Configure branch protection
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/branches/main/protection
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          required_status_checks: null
          enforce_admins: true
          required_pull_request_reviews: '{"required_approving_review_count": 1, "dismiss_stale_reviews": true, "require_code_owner_reviews": true, "require_last_push_approval": true}'
          restrictions: null
          required_linear_history: true
          allow_force_pushes: false
          allow_deletions: false
          required_conversation_resolution: true
          lock_branch: false
          allow_fork_syncing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 