name: ci-builds-and-releases

on:
  push:
    branches:
      - main
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - name: Log in to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      - name: Get repo name
        id: repo_vars
        run: echo "GH_REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      - name: Build and Push Docker Image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.GH_REPO_NAME }}:${{ env.SHORT_SHA }}, ${{ secrets.DOCKER_USERNAME }}/${{ env.GH_REPO_NAME }}:latest
          push: true
          platforms: 'linux/amd64,linux/arm64'
          labels: ${{ github.github_repository }}
  release:
    name: Create GitHub Release
    runs-on: ubuntu-20.04
    needs: build
    permissions:
      contents: write
      actions: read
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Get last 4 commits
        id: last_commits
        run: |
          printf "Changelogs:\n" > last_commits.txt
          git log -4 --pretty=format:"- %s (%h)" >> last_commits.txt
      - name: Determine next tag
        id: tag_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
          echo "Latest tag: $latest_tag"
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          patch=$((patch + 1))
          if [ "$patch" -ge 10 ]; then
            patch=0
            minor=$((minor + 1))
          fi
          if [ "$minor" -ge 10 ]; then
            minor=0
            major=$((major + 1))
          fi
          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "TAG_NAME=$new_tag" >> $GITHUB_ENV
      - name: Create and push new tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o yed
      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o yed.exe
      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          body_path: last_commits.txt
          tag_name: ${{ env.TAG_NAME }}
          files: |
            yed
            yed.exe
